version: "3.9"

services:
  httpserver:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEBIAN_VERSION: 10
        APP_VERSION: 1.0.1
    ports:
      - "8000:80"