FROM nginx:latest

# copy the configuration file for site `personal.localhost` from files/ directory
COPY files/nginx/default.conf /etc/nginx/conf.d/default.conf

# copy site files to /var/www/html
COPY files/site/ /var/www/html/
RUN chown -R nginx:nginx /var/www/html
