FROM debian AS build

RUN apt-get update && apt-get install -y gcc git

WORKDIR /src

RUN git clone https://github.com/nginx/unit.git

WORKDIR /src/unit

RUN ./configure --prefix=/usr --modules=php --libdir=/usr/lib/x86_64-linux-gnu && make all

FROM debian

COPY --from=build /src/unit/build/. /usr/

CMD ["unitd", "--no-daemon", "--control"]