version: "3.0"

services:
  frontend:
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    networks:
      - frontend
    depends_on:
      - backend
    volumes:
      - ./files/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./mounts/site:/var/www/html
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
  backend:
    build:
      context: ./files/php
    networks:
      - backend
      - frontend
    depends_on:
      - database
    volumes:
      - ./mounts/site:/var/www/html
    env_file:
      - mysql.env
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 8M
      restart_policy:
        condition: any
  database:
    image: mariadb:10.6
    env_file:
      - mysql.env
    networks:
      - backend
    volumes:
      - ./mounts/site/install/structure.sql:/docker-entrypoint-initdb.d/01_structure.sql
      - ./mounts/site/install/data.sql:/docker-entrypoint-initdb.d/02_data.sql
      - database:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

networks:
  frontend: {}
  backend: {}

volumes:
  database: {}
