version: "3.0"

services:
  backend:
    image: php:7.4-fpm
    volumes:
      - ./mounts/site:/var/www/html
    networks:
      - internal
  frontend:
    image: nginx:1.23-alpine
    ports:
      - "80:80"
    volumes:
      - ./mounts/site:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal
    depends_on:
      - backend

networks:
  internal: {}
